name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Pull docker composer image
        run: docker pull library/composer:latest
      - name: Install composer packages
        run: docker run --rm --volume $PWD:/app composer composer install
      - name: Build codeception actors
        run: docker run --rm --volume $PWD:/app composer vendor/bin/codecept build
      - name: Run test suite
        run: docker run --rm --volume $PWD:/app composer test
